[build]
  publish = "public"
  command = "npm run build"
  
[build.environment]
  NODE_VERSION = "10"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

# Redirect with a 302
[[redirects]]
  from = "/portfolio"
  to = "https://portfolio.edwardsmoses.com/"
  status = 302

[[redirects]]
  from = "/resume"
  to = "https://www.toptal.com/resume/edwards-moses"
  status = 302

[[redirects]]
  from = "/showcase"
  to = "https://portfolio.edwardsmoses.com/"
  status = 302

[[redirects]]
  from = "/hire-me"
  to = "https://portfolio.edwardsmoses.com/s/UZqEkRqv-full-stack-web-app-development"
  status = 302
  
  

  