[build]
  publish = "public"
  command = "npm run build"
  
[build.environment]
  NODE_VERSION = "10"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

# Redirect with a 302
[[redirects]]
  from = "/portfolio"
  to = "https://edwardsmoses.notion.site/Hey-I-m-Edwards-Moses-42fae7d7e5054601b11787407af84e75"
  status = 302

[[redirects]]
  from = "/resume/*"
  to = "https://edwardsmoses.notion.site/Hey-I-m-Edwards-Moses-42fae7d7e5054601b11787407af84e75/:splat"
  status = 302

[[redirects]]
  from = "/showcase"
  to = "https://contra.com/edwardsmosesi58z1tbl"
  status = 200
  force = true

  